### ISSUE TITLE
下载好功能包后，我catkin_make后说没有许可，我应该怎么处理？

### ISSUE THREAD

**Issue by 10179013** [tianbot/rmtt_ros#2]
环境：ros2go ubuntu 18.04

`[100%] Generating dynamic reconfigure files from config/tracker_pid.cfg: /home/tianbot/catkin_ws_tello/devel/include/rmtt_tracker/tracker_pidConfig.h /home/tianbot/catkin_ws_tello/devel/lib/python2.7/dist-packages/rmtt_tracker/cfg/tracker_pidConfig.py
../../catkin_generated/env_cached.sh: 16: exec: /home/tianbot/catkin_ws_tello/src/rmtt_ros/rmtt_tracker/config/tracker_pid.cfg: Permission denied
rmtt_ros/rmtt_tracker/CMakeFiles/rmtt_tracker_gencfg.dir/build.make:63: recipe for target '/home/tianbot/catkin_ws_tello/devel/include/rmtt_tracker/tracker_pidConfig.h' failed
make[2]: *** [/home/tianbot/catkin_ws_tello/devel/include/rmtt_tracker/tracker_pidConfig.h] Error 126
CMakeFiles/Makefile2:1162: recipe for target 'rmtt_ros/rmtt_tracker/CMakeFiles/rmtt_tracker_gencfg.dir/all' failed
make[1]: *** [rmtt_ros/rmtt_tracker/CMakeFiles/rmtt_tracker_gencfg.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j8 -l8" failed
`

**Comment by tianb03** [comment]
增加tracker_pid.cfg文件的可执行权限。
