### ISSUE TITLE
关于设置项目的问题。

### ISSUE THREAD

**Issue by MohamedAli-M** [tianbot/rmtt_ros#5]
你好，我最近买了4架无人机，想做蜂群测试。 我究竟如何使用这个存储库来使其工作？ 先感谢您。

**Comment by tianb03** [comment]
Hi we only support RoboMaster Tello Talent, and work with abc_swarm. The license can be purchased at tianbot.taobao.com.

We only have Chinese version video tutorial. If needed we could prepare for the English version.
